### ISSUE TITLE
Add a quick method to manually flush the GL command buffer?

### ISSUE THREAD

**Issue by aubade** [Jebbs/DSFMLC#7]
One little stumbling block I've found when working with DSFML in a multithreaded context is that when building a texture with updateFromPixels, the GL command buffer isn't automatically flushed, so I get occasional corrupt textures. 

To solve this, on my end I added a quick static method in DSFMLC and DSFML called Texture.flush() that just calls glCheck(glFlush()) on the C++-side, and i'm wondering if this is the sort of thing you think would be worth me filing a pull request for.

**Comment by Jebbs** [comment]
What do the C++ folks usually do I this situation? Link to OpenGL and call glFlush as well?

**Comment by aubade** [comment]
I admittedly have no idea; pulling in OpenGL and just making the raw call d-side would indeed work; I just didn't want to do this in my project since it'd be pulling in a whole new dependency for a single line.

**Comment by aubade** [comment]
But my impression from the SFML source is that you can use C++ SFML's own GL bindings from your own code; after all there's include/SFML/OpenGL.hpp, whereas with D you need to pull in dererelict-GL or similar

**Comment by Jebbs** [comment]
Closing this since it was added
